listen_port = 8448

[protocols."tls_ech"]
protocol = "tls"
target = ["1.1.1.1:53"] # default target to which the packet is sent when ECH decryption fails (no matching ECH config)
load_balance = "source_ip"
server_names = ["localhost"]

# Static ECH configuration embedded in the client source code
[protocols."tls_ech".ech]
ech_config_list = "ADz+DQA4ugAgACA9U8FCH7vKOFXVCCcAdpUUSfu3rzlooRNflhOXyV0uTwAEAAEAAQAJbG9jYWxob3N0AAA"
private_keys = ["KwyvZOuPlflYlcmJbwhA24HMWUvxXXyan/oh9cJ6lNw"]
# Acceptable private server names obtained from decrypted ECH Client Hello Inner, where port is optional.
# When port is not specified, it is the same as the listen port (i.e., forward as it is).
private_server_names = ["localhost:443"]
